#!/bin/bash
MANIFEST=https://github.com/arulebin/android_manifest.git
BRANCH=eleven

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice.Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name "arulebin"
git config --global user.email "ebinarul@protonmail.com"

git clone https://github.com/arulebin/local_manifest.git -b cph .repo/local_manifests

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)

# build rom
source build/envsetup.sh
export CIPHER_OFFICIAL=true
lunch lineage_rosy-userdebug
cd /tmp/rom
export CCACHE_DIR=/tmp/ccache  ##use additional flags if you need(optional)
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1

ccache -M 30G
ccache -o compression=true
ccache -z
ccache -c

up(){
        curl --upload-file $1 https://transfer.sh/
}

make_rom(){
        mka bacon -j8
        zip=$(up out/target/product/rosy/*zip)
        echo " "
        echo "$zip"
        curl -sL https://git.io/file-transfer | sh
        ./transfer wet out/target/product/rosy/*zip
}

make_rom


